# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/ZYNQ/Embedded_System/navigator_v2/7020/16_ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0.xci
# IP: The module: 'system_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ZYNQ/Embedded_System/navigator_v2/7020/16_ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/ZYNQ/Embedded_System/navigator_v2/7020/16_ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0.xci
# IP: The module: 'system_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ZYNQ/Embedded_System/navigator_v2/7020/16_ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
