// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Address.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Address_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Address_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Address_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Address_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Address_2eproto;
namespace NameSpaca_Address {
class CAddress;
struct CAddressDefaultTypeInternal;
extern CAddressDefaultTypeInternal _CAddress_default_instance_;
}  // namespace NameSpaca_Address
PROTOBUF_NAMESPACE_OPEN
template<> ::NameSpaca_Address::CAddress* Arena::CreateMaybeMessage<::NameSpaca_Address::CAddress>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace NameSpaca_Address {

// ===================================================================

class CAddress final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NameSpaca_Address.CAddress) */ {
 public:
  inline CAddress() : CAddress(nullptr) {}
  ~CAddress() override;
  explicit PROTOBUF_CONSTEXPR CAddress(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CAddress(const CAddress& from);
  CAddress(CAddress&& from) noexcept
    : CAddress() {
    *this = ::std::move(from);
  }

  inline CAddress& operator=(const CAddress& from) {
    CopyFrom(from);
    return *this;
  }
  inline CAddress& operator=(CAddress&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CAddress& default_instance() {
    return *internal_default_instance();
  }
  static inline const CAddress* internal_default_instance() {
    return reinterpret_cast<const CAddress*>(
               &_CAddress_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CAddress& a, CAddress& b) {
    a.Swap(&b);
  }
  inline void Swap(CAddress* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CAddress* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CAddress* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CAddress>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CAddress& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CAddress& from) {
    CAddress::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CAddress* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NameSpaca_Address.CAddress";
  }
  protected:
  explicit CAddress(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddrNameFieldNumber = 2,
    kAddrIdFieldNumber = 1,
  };
  // bytes addr_name = 2;
  void clear_addr_name();
  const std::string& addr_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_addr_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_addr_name();
  PROTOBUF_NODISCARD std::string* release_addr_name();
  void set_allocated_addr_name(std::string* addr_name);
  private:
  const std::string& _internal_addr_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_addr_name(const std::string& value);
  std::string* _internal_mutable_addr_name();
  public:

  // int32 addr_id = 1;
  void clear_addr_id();
  int32_t addr_id() const;
  void set_addr_id(int32_t value);
  private:
  int32_t _internal_addr_id() const;
  void _internal_set_addr_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:NameSpaca_Address.CAddress)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr addr_name_;
    int32_t addr_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Address_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CAddress

// int32 addr_id = 1;
inline void CAddress::clear_addr_id() {
  _impl_.addr_id_ = 0;
}
inline int32_t CAddress::_internal_addr_id() const {
  return _impl_.addr_id_;
}
inline int32_t CAddress::addr_id() const {
  // @@protoc_insertion_point(field_get:NameSpaca_Address.CAddress.addr_id)
  return _internal_addr_id();
}
inline void CAddress::_internal_set_addr_id(int32_t value) {
  
  _impl_.addr_id_ = value;
}
inline void CAddress::set_addr_id(int32_t value) {
  _internal_set_addr_id(value);
  // @@protoc_insertion_point(field_set:NameSpaca_Address.CAddress.addr_id)
}

// bytes addr_name = 2;
inline void CAddress::clear_addr_name() {
  _impl_.addr_name_.ClearToEmpty();
}
inline const std::string& CAddress::addr_name() const {
  // @@protoc_insertion_point(field_get:NameSpaca_Address.CAddress.addr_name)
  return _internal_addr_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CAddress::set_addr_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.addr_name_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:NameSpaca_Address.CAddress.addr_name)
}
inline std::string* CAddress::mutable_addr_name() {
  std::string* _s = _internal_mutable_addr_name();
  // @@protoc_insertion_point(field_mutable:NameSpaca_Address.CAddress.addr_name)
  return _s;
}
inline const std::string& CAddress::_internal_addr_name() const {
  return _impl_.addr_name_.Get();
}
inline void CAddress::_internal_set_addr_name(const std::string& value) {
  
  _impl_.addr_name_.Set(value, GetArenaForAllocation());
}
inline std::string* CAddress::_internal_mutable_addr_name() {
  
  return _impl_.addr_name_.Mutable(GetArenaForAllocation());
}
inline std::string* CAddress::release_addr_name() {
  // @@protoc_insertion_point(field_release:NameSpaca_Address.CAddress.addr_name)
  return _impl_.addr_name_.Release();
}
inline void CAddress::set_allocated_addr_name(std::string* addr_name) {
  if (addr_name != nullptr) {
    
  } else {
    
  }
  _impl_.addr_name_.SetAllocated(addr_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.addr_name_.IsDefault()) {
    _impl_.addr_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:NameSpaca_Address.CAddress.addr_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace NameSpaca_Address

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Address_2eproto
