// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Address.proto

#include "Address.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR CAddress::CAddress(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.addr_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.addr_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CAddressDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CAddressDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CAddressDefaultTypeInternal() {}
  union {
    CAddress _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CAddressDefaultTypeInternal _CAddress_default_instance_;
static ::_pb::Metadata file_level_metadata_Address_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Address_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Address_2eproto = nullptr;

const uint32_t TableStruct_Address_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CAddress, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CAddress, _impl_.addr_id_),
  PROTOBUF_FIELD_OFFSET(::CAddress, _impl_.addr_name_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::CAddress)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_CAddress_default_instance_._instance,
};

const char descriptor_table_protodef_Address_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rAddress.proto\".\n\010CAddress\022\017\n\007addr_id\030\001"
  " \001(\005\022\021\n\taddr_name\030\002 \001(\014b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Address_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Address_2eproto = {
    false, false, 71, descriptor_table_protodef_Address_2eproto,
    "Address.proto",
    &descriptor_table_Address_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_Address_2eproto::offsets,
    file_level_metadata_Address_2eproto, file_level_enum_descriptors_Address_2eproto,
    file_level_service_descriptors_Address_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Address_2eproto_getter() {
  return &descriptor_table_Address_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Address_2eproto(&descriptor_table_Address_2eproto);

// ===================================================================

class CAddress::_Internal {
 public:
};

CAddress::CAddress(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CAddress)
}
CAddress::CAddress(const CAddress& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CAddress* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.addr_name_){}
    , decltype(_impl_.addr_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.addr_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.addr_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_addr_name().empty()) {
    _this->_impl_.addr_name_.Set(from._internal_addr_name(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.addr_id_ = from._impl_.addr_id_;
  // @@protoc_insertion_point(copy_constructor:CAddress)
}

inline void CAddress::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.addr_name_){}
    , decltype(_impl_.addr_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.addr_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.addr_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CAddress::~CAddress() {
  // @@protoc_insertion_point(destructor:CAddress)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CAddress::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.addr_name_.Destroy();
}

void CAddress::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CAddress::Clear() {
// @@protoc_insertion_point(message_clear_start:CAddress)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.addr_name_.ClearToEmpty();
  _impl_.addr_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CAddress::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 addr_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.addr_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes addr_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_addr_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CAddress::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CAddress)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 addr_id = 1;
  if (this->_internal_addr_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_addr_id(), target);
  }

  // bytes addr_name = 2;
  if (!this->_internal_addr_name().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_addr_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CAddress)
  return target;
}

size_t CAddress::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CAddress)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes addr_name = 2;
  if (!this->_internal_addr_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_addr_name());
  }

  // int32 addr_id = 1;
  if (this->_internal_addr_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_addr_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CAddress::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CAddress::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CAddress::GetClassData() const { return &_class_data_; }


void CAddress::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CAddress*>(&to_msg);
  auto& from = static_cast<const CAddress&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CAddress)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_addr_name().empty()) {
    _this->_internal_set_addr_name(from._internal_addr_name());
  }
  if (from._internal_addr_id() != 0) {
    _this->_internal_set_addr_id(from._internal_addr_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CAddress::CopyFrom(const CAddress& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CAddress)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CAddress::IsInitialized() const {
  return true;
}

void CAddress::InternalSwap(CAddress* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.addr_name_, lhs_arena,
      &other->_impl_.addr_name_, rhs_arena
  );
  swap(_impl_.addr_id_, other->_impl_.addr_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CAddress::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Address_2eproto_getter, &descriptor_table_Address_2eproto_once,
      file_level_metadata_Address_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CAddress*
Arena::CreateMaybeMessage< ::CAddress >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CAddress >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
