/*************************************************
Copyright (C), 2009-2012    , Level Chip Co., Ltd.
文件名:	Device.c
作  者:	钱锐      版本: V0.1.0     新建日期: 2024.02.19
描  述: 封装一些简易处理
备  注:
修改记录:

  1.  日期: 2024.02.19
	  作者: 钱锐
	  内容:
		  1) 此为模板第一个版本;
	  版本:V0.1.0

*************************************************/

#include <wdm.h>

#include "Device.h"
#include "Dispatch.h"

PDEVICE_OBJECT GetDeviceObjectByName(IN PCWSTR _pDevicePath)
{
	NTSTATUS lNTStatus = STATUS_SUCCESS;
	UNICODE_STRING tDeviceName;
	PFILE_OBJECT ptFileObj = NULL;
	PDEVICE_OBJECT ptDevObj = NULL;

	RtlInitUnicodeString(&tDeviceName, _pDevicePath);

	lNTStatus = IoGetDeviceObjectPointer(&tDeviceName, FILE_ANY_ACCESS, &ptFileObj, &ptDevObj);		//函数只会增加对 ptFileObj 的引用计数
	if (!NT_SUCCESS(lNTStatus) || !ptFileObj || !ptDevObj)
	{
		KdPrint(("获取设备对象指针出错, 0x%x\n", lNTStatus));
		return NULL;
	}

	ObDereferenceObject(ptFileObj);
	ptFileObj = NULL;

	ObReferenceObject(ptDevObj);

	return ptDevObj;
}

PDEVICE_OBJECT CreateNewDeviceAndAttachedToPDO(IN PDRIVER_OBJECT _pDriverObject, IN PDEVICE_OBJECT _pPDO)
{
	if (!_pDriverObject || !_pPDO)
	{
		KdPrint(("CreateNewDeviceAndAttachedToPDO input param is err.\n"));
		return NULL;
	}

	NTSTATUS lNTStatus = STATUS_SUCCESS;
	PDEVICE_OBJECT ptFDO = NULL;
	PDEVICEEXTENSION ptDevExtension = NULL;

	lNTStatus = IoCreateDevice(_pDriverObject, sizeof(DEVICEEXTENSION), NULL, FILE_DEVICE_UNKNOWN, FILE_AUTOGENERATED_DEVICE_NAME, FALSE, &ptFDO);
	if (!NT_SUCCESS(lNTStatus))
	{
		KdPrint(("IoCreateDevice is err.\n"));
		return NULL;
	}

	ptDevExtension = ptFDO->DeviceExtension;

	RtlFillMemory(ptDevExtension, sizeof(*ptDevExtension), 0);
	RtlCopyMemory(ptDevExtension->IORemoveLock_Tag, "1gaT", strlen("1gaT"));							//一般使用4个方向的Tag1、Tag2、Tag3...Tagn字符

	IoInitializeRemoveLock(&ptDevExtension->IORemoveLock, '1gaT', 0, 0);								//一般使用4个方向的Tag1、Tag2、Tag3...Tagn字符

	ptDevExtension->pFDO = IoAttachDeviceToDeviceStack(ptFDO, _pPDO);
	if (ptDevExtension->pFDO == NULL)
	{
		KdPrint(("IoAttachDeviceToDeviceStack is err\n"));
		return NULL;
	}

	ptFDO->Characteristics = ptDevExtension->pFDO->Characteristics;
	ptFDO->DeviceType = ptDevExtension->pFDO->DeviceType;
	ptFDO->Flags = ptDevExtension->pFDO->Flags;
	ptFDO->Flags &= ~DO_DEVICE_INITIALIZING;

	for (size_t i = 0; i <= IRP_MJ_MAXIMUM_FUNCTION; i++)
	{
		_pDriverObject->MajorFunction[i] = Dispatch_Default;											//过滤驱动必须实现所有的派遣函数
	}
	_pDriverObject->MajorFunction[IRP_MJ_WRITE] = Dispatch_Write;
	_pDriverObject->MajorFunction[IRP_MJ_PNP] = Dispatch_Pnp;
	_pDriverObject->MajorFunction[IRP_MJ_POWER] = Dispatch_Power;

	return ptDevExtension->pFDO;
}
