/*************************************************
Copyright (C), 2009-2012    , Level Chip Co., Ltd.
文件名:	main.c
作  者:	钱锐      版本: V0.1.0     新建日期: 2024.12.18
描  述: io定时器与dpc定时器
备  注:	1、io定时器时间间隔固定为1秒钟
		2、dpc定时器可以设置时间间隔（其定时精度在us级别）

		io定时器API:
			IoInitializeTimer--初始化定时器
			IoStartTimer--启动定时器
			IoStopTimer--停止定时器

		dpc定时器API:
			KeInitializeTimer--初始化定时器
			KeInitializeDpc--初始化dpc
			KeSetTimer--启动一次时延调用函数操作
			KeCancelTimer--计时器间隔（如果已设置）过期之前将计时器对象取消排队
修改记录:

  1.  日期: 2024.12.18
	  作者: 钱锐
	  内容:
		  1) 此为模板第一个版本;
	  版本:V0.1.0

*************************************************/

#include <ntddk.h>

#ifdef _DPC_TIMER
KTIMER g_tKTimer;
KDPC g_tkDpc;
LARGE_INTEGER g_tTimeout;		//DPC定时器间隔

VOID DPC_Timer_Routine(_In_ struct _KDPC* Dpc, _In_opt_ PVOID DeferredContext, _In_opt_ PVOID SystemArgument1, _In_opt_ PVOID SystemArgument2)
{
	KdPrint(("DPC_Timer_Routine is called.\n"));
	KeSetTimer(&g_tKTimer, g_tTimeout, &g_tkDpc);
}

#else
VOID IO_Timer_Routine(_In_ struct _DEVICE_OBJECT* DeviceObject, _In_opt_ PVOID Context)
{
	KdPrint(("IO_Timer_Routine is called.\n"));
}
#endif // _DPC_TIMER



VOID DriverUnload(IN PDRIVER_OBJECT DriverObject)
{
	KdPrint(("驱动卸载成功\n"));

	if (DriverObject->DeviceObject)
	{
#ifdef _DPC_TIMER
		KeCancelTimer(&g_tKTimer);
#else
		IoStopTimer(DriverObject->DeviceObject);
#endif // _DPC_TIMER
		
		IoDeleteDevice(DriverObject->DeviceObject);
	}
}

NTSTATUS DriverEntry(IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
{
	NTSTATUS lNTStatus = STATUS_SUCCESS;
	PDEVICE_OBJECT ptDeviceObj = NULL;
	

	KdPrint(("驱动加载成功\n"));

	DriverObject->DriverUnload = DriverUnload;
	
	//创建一个设备对象，其设备对象名称有操作系统自动生成
	lNTStatus = IoCreateDevice(DriverObject, 0, NULL, FILE_DEVICE_UNKNOWN, FILE_AUTOGENERATED_DEVICE_NAME, FALSE, &ptDeviceObj);
	if(!NT_SUCCESS(lNTStatus))
	{
		KdPrint(("创建设备对象失败\n"));
		return lNTStatus;
	}

#ifdef _DPC_TIMER		//DPC定时器测试
	KeInitializeTimer(&g_tKTimer);
	KeInitializeDpc(&g_tkDpc, DPC_Timer_Routine, NULL);

	g_tTimeout = RtlConvertLongToLargeInteger(-10 * 200 * 1000);
	KeSetTimer(&g_tKTimer, g_tTimeout, &g_tkDpc);
#else					//IO定时器测试
	IoInitializeTimer(ptDeviceObj, IO_Timer_Routine, NULL);
	IoStartTimer(ptDeviceObj);
#endif // _DPC_TIMER

	return lNTStatus;
}



